# 1. Create a 3x3x3 array with random values 

In [98]:
import numpy as np
np.random.rand(3,3,3)

array([[[0.08967092, 0.92458036, 0.072161  ],
        [0.55236336, 0.56539161, 0.38627148],
        [0.26045856, 0.88444914, 0.57342337]],

       [[0.75810608, 0.65125996, 0.49851392],
        [0.66480477, 0.02158957, 0.10000591],
        [0.60612083, 0.341515  , 0.21501819]],

       [[0.49673548, 0.85507221, 0.44619082],
        [0.28838952, 0.52026568, 0.84308217],
        [0.02667328, 0.30174301, 0.66450752]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [15]:
seq = np.diag(1+np.arange(4),k=-1)
print(seq)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [22]:
chk = np.zeros((8,8),dtype=int)
chk[1::2,::2] = 1
chk[::2,1::2] = 1
print(chk)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [28]:
Norm = np.random.random((5,5))
print(Norm)
print("-----------------")
Normmax, Normmin = Norm.max(), Norm.min()
print(Normmax)
print(Normmin)
Norm = (Norm - Normmin)/(Normmax - Normmin)
print(Norm)

[[0.85873296 0.25978277 0.4956988  0.92473465 0.87267366]
 [0.4460599  0.30214213 0.4591329  0.14285151 0.04829091]
 [0.63519194 0.23589348 0.10779472 0.43435894 0.68147312]
 [0.32150218 0.19123312 0.73536388 0.54138232 0.44456263]
 [0.67400214 0.96637872 0.98344754 0.95330748 0.70807429]]
-----------------
0.9834475433247811
0.04829091206818403
[[0.86663776 0.22615661 0.47843096 0.93721598 0.88154511]
 [0.42535012 0.27145316 0.4393296  0.10111739 0.        ]
 [0.6275965  0.20061086 0.06362978 0.41283782 0.67708679]
 [0.29215562 0.15285377 0.73471432 0.52728216 0.42374903]
 [0.66909778 0.98174763 1.         0.96777004 0.70553248]]


# 5.  How to find common values between two arrays?

In [30]:
comm1 = np.random.randint(0,10,10)
print(comm1)
comm2 = np.random.randint(0,10,10)
print(comm2)
print(np.intersect1d(comm1,comm2))

[6 7 5 7 6 1 6 5 8 1]
[9 2 8 4 6 8 8 4 8 6]
[6 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [32]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2020-07-24
2020-07-25
2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [97]:
C = np.random.randint(0,1,5)
D = np.random.randint(0,2,5)
print(C)
print(D)
equal1 = np.allclose(C,D)
equal2 = np.array_equal(C,D)
print(equal1)
print(equal2)
A =np.array([[1,2,3],[4,5,6]])
B =np.array([[1,2,3],[4,5,6]])
equal = np.allclose(A,B)
equal3 = np.array_equal(A,B)
print(equal)
print(equal3)

[0 0 0 0 0]
[0 1 0 1 0]
False
False
True
True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [91]:
randmax = np.random.random(10)
print(randmax)
randmax[randmax.argmax()] = 0
print(randmax)

[0.29321657 0.03227828 0.26262314 0.33910312 0.31520332 0.53454809
 0.93480417 0.45636139 0.6885356  0.06031931]
[0.29321657 0.03227828 0.26262314 0.33910312 0.31520332 0.53454809
 0.         0.45636139 0.6885356  0.06031931]


# 9. How to print all the values of an array?

In [79]:
np.set_printoptions(threshold=np.inf)
my_array = np.zeros((16,16))
print(my_array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [67]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 0.34093589 -0.4681448  -0.32805015 -0.1233923   0.43156329 -0.31628938
   0.47376586  0.08618301  0.00715692 -0.10372833]
 [ 0.11193784 -0.27406838  0.07024466  0.0975906  -0.40481746  0.16743595
  -0.09984552 -0.24058119 -0.00350098  0.57560449]
 [ 0.00187763  0.35985124 -0.45499558  0.26839373  0.05130189 -0.50942936
   0.00548684  0.10980388  0.13929636  0.02841337]
 [ 0.21334357 -0.40864231  0.02028321  0.16384545  0.34998394 -0.39866285
  -0.1165171  -0.32735157  0.30139883  0.20231883]
 [-0.51307034  0.29338281  0.28327954 -0.18313459  0.45674512 -0.26379108
  -0.0806035  -0.00543694 -0.02392823  0.0365572 ]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [64]:
a1 = np.ones(10)
print(a1)
a2 = np.random.randint(0,len(a1),20)
print(a2)
a1 += np.bincount(a2, minlength=len(a1))
print(a1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 4 5 6 9 4 7 8 9 4 2 0 1 4 2 1 2 4 6 5]
None
[ 3.  5.  7.  1. 11.  7.  5.  3.  3.  5.]


# 12.How to get the diagonal of a dot product?

In [56]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
print(np.diag(np.diag(np.dot(A, B))))
#np.random.rand(3,3)
#A = np.random.random((5,5))
C = np.random.random((5,5))
D = np.random.random((5,5))
print(C)
print(D)
print(np.diag(np.diag(np.dot(C, D))))

[[0.5522706  0.47852125 0.12711768 0.72329463 0.69742456]
 [0.24023653 0.44773712 0.84318749 0.98898573 0.78786632]
 [0.11292106 0.93420016 0.66573368 0.17506378 0.66653458]
 [0.09164641 0.82091662 0.68035869 0.87165285 0.86338592]
 [0.42237721 0.57404427 0.97370868 0.76755415 0.48377011]]
[[0.56724289 0.46708064 0.43801541 0.48150494 0.56440134]
 [0.35369196 0.30064245 0.51848524 0.49716762 0.26504904]
 [0.59336213 0.67647817 0.34536414 0.88658115 0.91302718]
 [0.19620942 0.21952703 0.67832105 0.57314502 0.93880912]
 [0.47290858 0.41563604 0.31773286 0.80164127 0.57388261]]
[[1.02968279 0.         0.         0.         0.        ]
 [0.         1.36179127 0.         0.         0.        ]
 [0.         0.         1.09428008 0.         0.        ]
 [0.         0.         0.         2.24716383 0.        ]
 [0.         0.         0.         0.         2.27777673]]
[[0.7061721  0.35731968 0.56840663 0.80711444 0.61322685]
 [0.22997664 0.14959032 0.22499891 0.0710586  0.06201162]
 [0.3792416

# 13.How to find the most frequent value in an array?

In [37]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[5 3 5 8 1 4 3 8 5 0 7 2 2 6 7 0 6 4 3 5 9 9 2 1 2 7 4 6 9 4 6 0 3 1 6 1 6
 1 2 0 4 2 7 7 9 8 6 9 4 0]
6


# 14.How to get the n largest values of an array

In [34]:
Z = np.arange(10000)
np.random.shuffle(Z)
print(Z)
n = 5

# Slow

print (Z[np.argsort(Z)[-n:]])

# Fast

print (Z[np.argpartition(-Z,n)[:n]])

[6284 4010 7136 ... 3374 7164 3170]
[9995 9996 9997 9998 9999]
[9997 9998 9999 9996 9995]


# 15.How to create a record array from a regular array?

In [57]:
arr = np.array([("Hello", 2.5, 3),

("World", 3.6, 2)])

Recarr = np.core.records.fromarrays(arr.T,

names='col1, col2, col3',

formats = 'S8, f8, i8')

print(Recarr)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
